language: go

go:
  - 1.6
  - master

before_install:
  - go get -t -v ./...

install: go get -v

notifications:
  email: false

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)